### ISSUE TITLE
Suggestion: .ping()

### ISSUE THREAD

**Issue by StellaraUmbrix** [freetnt5852/ladybug-fetch#3]
Receives ping of the response. Simple, but idk that much JavaScript, else I would make a PR

**Comment by IceeMC** [comment]
lol

**Comment by ravener** [comment]
That's not really a good idea, i mean its simple to already do that, just do some math with when respond arrived, however it may not be exact since it has to read whole body before resolving, you could do some simple raw http requests for a quick response time

**Comment by StellaraUmbrix** [comment]
wut

**Comment by IceeMC** [comment]
lmao
